apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: attestationhubserver-sm
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: attestationhubserver
  namespaceSelector:
    matchNames: ["attestationhub"]
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
