info:
  app:
    name: AttestationHubServer
    description: AttestationHub Server
server:
 port: 9090
 compression.enabled: true
 servlet:
   context-path: /attestationhubserver

springdoc:
   api-docs:
     enabled: true 
spring:
  profiles:
    active: local
  banner:
    location: classpath:attestationhubserver.txt
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2
      settings:
       web-allow-others: true
  datasource:
    url: jdbc:h2:file:/data/attestationhub;DB_CLOSE_ON_EXIT=FALSE
    username: attestationhub
    password: attestationhub
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect