spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:h2:file:/data/attestationhub;DB_CLOSE_ON_EXIT=FALSE
    username: attestationhub
    password: attestationhub
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
