replicas: 1

# Request modest resources for a small cluster
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

# Single-node persistence on gp3
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi

# Avoid strict anti-affinity for single-node
antiAffinity: "soft"
