backend:
  type: es
  es:
    host: elasticsearch-master.logging.svc.cluster.local
    port: 9200
    index: fluentbit
resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
