apiVersion: apps/v1
kind: Deployment
metadata:
  name: attestationhubserver
  namespace: attestationhub
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: attestationhubserver
  template:
    metadata:
      labels:
        app: attestationhubserver
    spec:
      securityContext:
        fsGroup: 1000           # so the app can write to /data
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: attestationhubserver
          image: 211125412565.dkr.ecr.us-east-2.amazonaws.com/fcb-attestationhub-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
          # optional but recommended
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: attestationhub-data
