apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attestationhub-data
  namespace: attestationhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
