apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attestationhub-data
  namespace: attestationhub
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
