apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attestationhub-data
  namespace: attestationhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi   # logical quota for the access point; EFS is elastic
